[library.bonfire-library]
location = build/fusesoc_libraries/bonfire-library
sync-uri = https://github.com/bonfireprocessor/bonfire-library.git
sync-type = git
auto-sync = true
[library.bonfire-core]
location = fusesoc-cores
sync-type = local

