-- File: tb_barrel_left_shift_comb.vhd
-- Generated by MyHDL 0.11
-- Date: Sat Aug  3 20:11:06 2019


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity tb_barrel_left_shift_comb is
end entity tb_barrel_left_shift_comb;


architecture MyHDL of tb_barrel_left_shift_comb is



signal d_in: unsigned(31 downto 0);
signal d_o: unsigned(31 downto 0);
signal shift_i: unsigned(4 downto 0);

begin


d_in <= unsigned'("00000000000000000000000000000001");


TB_BARREL_LEFT_SHIFT_COMB_STIMULUS: process is
begin
    for i in 0 to 32-1 loop
        shift_i <= to_unsigned(i, 5);
        wait for 10 * 1 ns;
        assert (d_o = shift_left(d_in, i))
            report "*** AssertionError ***"
            severity error;
        wait for 10 * 1 ns;
    end loop;
    wait;
end process TB_BARREL_LEFT_SHIFT_COMB_STIMULUS;

TB_BARREL_LEFT_SHIFT_COMB_LEFT_SHIFT_COMB0_COMB: process (d_in, shift_i) is
    variable p: natural;
    variable shift: integer;
    variable temp: unsigned(31 downto 0);
    variable fill: unsigned(31 downto 0);
begin
    p := 0;
    temp := d_in(32-1 downto 0);
    fill := unsigned'("00000000000000000000000000000000");
    for i in 0 to (5 - 0)-1 loop
        shift := (2 ** p);
        if (shift_i(i) = '1') then
            temp(32-1 downto 0) := resize(unsigned'(temp((32 - shift)-1 downto 0) & fill((2 ** p)-1 downto 0)), 32);
        end if;
        p := (p + 1);
    end loop;
    d_o <= temp;
end process TB_BARREL_LEFT_SHIFT_COMB_LEFT_SHIFT_COMB0_COMB;

end architecture MyHDL;
