#ifndef BONFIRE_PLATFORM_CMODS7_H
#define BONFIRE_PLATFORM_CMODS7_H

#include "common.h"

#define BONFIRE_PLATFORM_NAME "cmods7"
#define BONFIRE_SYSCLK_HZ 96000000u
#define BONFIRE_SRAM_BASE BONFIRE_BRAM_BASE
#define BONFIRE_SRAM_SIZE 65536u
#define BONFIRE_NUM_LEDS 4u
#define BONFIRE_LED_ACTIVE_LOW 0u
#define BONFIRE_LED_SHIFT 22u
#define BONFIRE_UART_BAUD BONFIRE_DEFAULT_BAUDRATE

#endif
