#ifndef BONFIRE_SOC_COMMON_H
#define BONFIRE_SOC_COMMON_H

#define BONFIRE_WISHBONE_BASE 0x40000000u
#define BONFIRE_NATIVE_IO_BASE 0x80000000u
#define BONFIRE_BRAM_BASE 0xc0000000u

#define BONFIRE_SOC_IO_OFFSET 0x00010000u

#define BONFIRE_UART0_BASE BONFIRE_WISHBONE_BASE
#define BONFIRE_SPI_FLASH_BASE (BONFIRE_WISHBONE_BASE + BONFIRE_SOC_IO_OFFSET)
#define BONFIRE_UART1_BASE (BONFIRE_WISHBONE_BASE + (2u * BONFIRE_SOC_IO_OFFSET))
#define BONFIRE_GPIO_BASE (BONFIRE_WISHBONE_BASE + (3u * BONFIRE_SOC_IO_OFFSET))

#define BONFIRE_LED_BASE BONFIRE_NATIVE_IO_BASE

#define BONFIRE_DEFAULT_BAUDRATE 38400u
#define BONFIRE_ENABLE_GPIO 1u

#endif
