#ifndef BONFIRE_PLATFORM_FIREANT_H
#define BONFIRE_PLATFORM_FIREANT_H

#include "common.h"

#define BONFIRE_PLATFORM_NAME "fireant"
#define BONFIRE_SYSCLK_HZ 25000000u
#define BONFIRE_SRAM_BASE BONFIRE_BRAM_BASE
#define BONFIRE_SRAM_SIZE 8192u
#define BONFIRE_NUM_LEDS 4u
#define BONFIRE_LED_ACTIVE_LOW 1u
#define BONFIRE_LED_SHIFT 22u
#define BONFIRE_UART_BAUD 115200u

#endif
