#ifndef BONFIRE_PLATFORM_ICEPIZERO_H
#define BONFIRE_PLATFORM_ICEPIZERO_H

#include "common.h"

#define BONFIRE_PLATFORM_NAME "icepizero"
#define BONFIRE_SYSCLK_HZ 50000000u
#define BONFIRE_SRAM_BASE BONFIRE_BRAM_BASE
#define BONFIRE_SRAM_SIZE 8192u
#define BONFIRE_NUM_LEDS 5u
#define BONFIRE_LED_ACTIVE_LOW 0u
#define BONFIRE_LED_SHIFT 21u
#define BONFIRE_UART_BAUD 115200
#undef BONFIRE_ENABLE_GPIO
#define BONFIRE_ENABLE_GPIO 1u

#endif
