#ifndef BONFIRE_PLATFORM_SIM_H
#define BONFIRE_PLATFORM_SIM_H

#include "common.h"

#define BONFIRE_PLATFORM_NAME "sim"
#define BONFIRE_SYSCLK_HZ 25000000u
#define BONFIRE_SRAM_BASE BONFIRE_BRAM_BASE
#define BONFIRE_SRAM_SIZE 8192u
#define BONFIRE_NUM_LEDS 8u
#define BONFIRE_LED_ACTIVE_LOW 0u
#define BONFIRE_LED_SHIFT 0u
#define BONFIRE_UART_BAUD 115200u

#endif
