#ifndef BONFIRE_PLATFORM_ULX3S_H
#define BONFIRE_PLATFORM_ULX3S_H

#include "common.h"

#define BONFIRE_PLATFORM_NAME "ulx3s"
#define BONFIRE_SYSCLK_HZ 62500000u
#define BONFIRE_SRAM_BASE BONFIRE_BRAM_BASE
#define BONFIRE_SRAM_SIZE 8192u
#define BONFIRE_NUM_LEDS 8u
#define BONFIRE_LED_ACTIVE_LOW 0u
#define BONFIRE_LED_SHIFT 22u
#define BONFIRE_UART_BAUD 115200u

#endif
