#ifndef BONFIRE_GPIO_H
#define BONFIRE_GPIO_H

#define BONFIRE_GPIO_INPUT_VAL 0x00u
#define BONFIRE_GPIO_INPUT_EN 0x04u
#define BONFIRE_GPIO_OUTPUT_EN 0x08u
#define BONFIRE_GPIO_OUTPUT_VAL 0x0cu
#define BONFIRE_GPIO_OUTPUT_XOR 0x40u

#endif
