#ifndef BONFIRE_SPI_H
#define BONFIRE_SPI_H

#define BONFIRE_SPI_CONTROL 0x00u
#define BONFIRE_SPI_STATUS 0x04u
#define BONFIRE_SPI_TX 0x08u
#define BONFIRE_SPI_RX 0x0cu
#define BONFIRE_SPI_CLOCK 0x10u
#define BONFIRE_SPI_PORT_STRIDE 0x40u

#define BONFIRE_SPI_CONTROL_CS 0x01u
#define BONFIRE_SPI_CONTROL_AUTOWAIT 0x02u

#define BONFIRE_SPI_STATUS_BUSY 0x01u
#define BONFIRE_SPI_STATUS_RX_READY 0x02u

#endif
