"""
Shared debug-module constants and DMI register map definitions.
(c) 2026 The Bonfire Project
License: See LICENSE
"""

# DMI opcodes
DMI_OP_NOP = 0
DMI_OP_READ = 1
DMI_OP_WRITE = 2
DMI_OP_SUCCESS = 0
DMI_OP_BUSY = 3

# DTMCS
DTM_VERSION = 1
DTM_IDLE = 1
DTMCS_DMIRESET_BIT = 16

# DMI register map
DMI_ADDR_DATA0 = 0x04
DMI_ADDR_DMCONTROL = 0x10
DMI_ADDR_DMSTATUS = 0x11
DMI_ADDR_HARTINFO = 0x12
DMI_ADDR_ABSTRACTCS = 0x16
DMI_ADDR_COMMAND = 0x17
DMI_ADDR_ABSTRACTAUTO = 0x18
DMI_ADDR_PROGBUF0 = 0x20
DMI_ADDR_PROGBUF1 = 0x21

# dmcontrol bit fields
DMCONTROL_DMACTIVE_BIT = 0
DMCONTROL_NDMRESET_BIT = 1
DMCONTROL_RESUMEREQ_BIT = 30
DMCONTROL_HALTREQ_BIT = 31

# dmstatus bit fields
DMSTATUS_AUTHENTICATED_BIT = 7
DMSTATUS_ANYHALTED_BIT = 8
DMSTATUS_ALLHALTED_BIT = 9
DMSTATUS_ANYRUNNING_BIT = 10
DMSTATUS_ALLRUNNING_BIT = 11
DMSTATUS_ANYRESUMEACK_BIT = 16
DMSTATUS_ALLRESUMEACK_BIT = 17
DMSTATUS_IMPBREAK_BIT = 22

# hartinfo field ranges
HARTINFO_NSCRATCH_MSB = 24
HARTINFO_NSCRATCH_LSB = 20
HARTINFO_DATAACCESS_MSB = 16
HARTINFO_DATAACCESS_LSB = 12

# abstractcs field ranges
ABSTRACTCS_PROGBUFSIZE_MSB = 29
ABSTRACTCS_PROGBUFSIZE_LSB = 24
ABSTRACTCS_BUSY_BIT = 12
ABSTRACTCS_CMDERR_MSB = 11
ABSTRACTCS_CMDERR_LSB = 8
ABSTRACTCS_DATACOUNT_MSB = 4
ABSTRACTCS_DATACOUNT_LSB = 0

# abstract command field ranges
COMMAND_TYPE_MSB = 32
COMMAND_TYPE_LSB = 24
COMMAND_AARSIZE_MSB = 23
COMMAND_AARSIZE_LSB = 20
COMMAND_AARPOSTINCREMENT_BIT = 19
COMMAND_POSTEXEC_BIT = 18
COMMAND_TRANSFER_BIT = 17
COMMAND_WRITE_BIT = 16
COMMAND_REGNO_MSB = 5
COMMAND_REGNO_LSB = 0

# abstractauto split
ABSTRACTAUTO_PROGBUF_BASE = 16

# cmderr values
CMDERR_NONE = 0
CMDERR_BUSY = 1
CMDERR_NOT_SUPPORTED = 2
CMDERR_HART_RUNNING = 4
