"""
Shared debug-module constants and DMI register map definitions.
(c) 2026 The Bonfire Project
License: See LICENSE
"""

# DMI opcodes
DMI_OP_NOP = 0
DMI_OP_READ = 1
DMI_OP_WRITE = 2
DMI_OP_SUCCESS = 0
DMI_OP_BUSY = 3

# DTMCS
DTM_VERSION = 1
DTM_IDLE = 1

# DMI register map
DMI_ADDR_DATA0 = 0x04
DMI_ADDR_DMCONTROL = 0x10
DMI_ADDR_DMSTATUS = 0x11
DMI_ADDR_HARTINFO = 0x12
DMI_ADDR_ABSTRACTCS = 0x16
DMI_ADDR_COMMAND = 0x17
DMI_ADDR_ABSTRACTAUTO = 0x18
DMI_ADDR_PROGBUF0 = 0x20
DMI_ADDR_PROGBUF1 = 0x21

# cmderr values
CMDERR_NONE = 0
CMDERR_BUSY = 1
CMDERR_NOT_SUPPORTED = 2
CMDERR_HART_RUNNING = 4
