"""
RISC-V debug module — DMI interface and abstract command protocol
(c) 2023 The Bonfire Project
License: See LICENSE
"""
from __future__ import annotations

from typing import Any

from myhdl import Signal, block, always, always_comb, instances, modbv

import rtl.debug.constants as constants
from rtl.debug.dm_registers import DebugModuleRegisterBundle, DmiBundle
from rtl.debug.types import (
    t_abstract_command_state,
    t_abstract_command_type,
    t_debug_hart_state,
    DEBUG_SPEC_VERSION,
)
from rtl.type_aliases import BitSignal
from util.diagnostics import get_diagnostics


class DebugModuleInterface:
    def __init__(self, config: Any) -> None:
        self.config = config
        xlen = config.xlen
        self.xlen = xlen

    @block
    def dmi_interface(
        self,
        dtm: DmiBundle,
        debugRegs: DebugModuleRegisterBundle,
        clock: BitSignal,
    ) -> Any:
        """
        dtm: DmiBundle
        debugRegs: DebugModuleRegisterBundle
        """
        get_diagnostics().detail("dmi_interface: numdata={} progbuf_size={} dmi_adr_width={}".format(
            self.config.numdata,
            self.config.progbuf_size,
            self.config.dmi_adr_width,
        ))

        debug_regs = debugRegs
        command_start_error = Signal(modbv(0)[3:])

        @always_comb
        def command_state_decode():
            if debug_regs.abstract_command_state != t_abstract_command_state.none:
                command_start_error.next = constants.CMDERR_BUSY
            elif debug_regs.hart_state == t_debug_hart_state.running:
                command_start_error.next = constants.CMDERR_HART_RUNNING
            else:
                command_start_error.next = constants.CMDERR_NONE

        @always(clock.posedge)
        def seq():
            dtm.ndmreset.next = debug_regs.ndmreset

            # Request completion bookkeeping shared by haltreq and resumereq.
            if debug_regs.req_ack:
                if debug_regs.resumereq:
                    debug_regs.resumeack.next = True

                debug_regs.haltreq.next = False
                debug_regs.resumereq.next = False

            # Abstract command lifecycle updates generated by the debug core.
            if debug_regs.abstract_command_state == t_abstract_command_state.regvalid:
                debug_regs.data_regs[0].next = debug_regs.abstract_command_result
            elif debug_regs.abstract_command_state == t_abstract_command_state.taken:
                debug_regs.abstract_command_new.next = False

            dtm.dbo.next = 0
            if dtm.en:
                is_data_reg = (dtm.adr >= constants.DMI_ADDR_DATA0) and (
                    dtm.adr <= constants.DMI_ADDR_DATA0 + self.config.numdata - 1
                )

                if not dtm.we:
                    # Status and control register reads.
                    if dtm.adr == constants.DMI_ADDR_DMSTATUS:
                        dtm.dbo.next[22] = True
                        dtm.dbo.next[17] = debug_regs.resumeack
                        dtm.dbo.next[16] = debug_regs.resumeack
                        dtm.dbo.next[11] = debug_regs.hart_state == t_debug_hart_state.running
                        dtm.dbo.next[10] = debug_regs.hart_state == t_debug_hart_state.running
                        dtm.dbo.next[9] = debug_regs.hart_state == t_debug_hart_state.halted
                        dtm.dbo.next[8] = debug_regs.hart_state == t_debug_hart_state.halted
                        dtm.dbo.next[7] = True
                        dtm.dbo.next[4:] = DEBUG_SPEC_VERSION
                    elif dtm.adr == constants.DMI_ADDR_DMCONTROL:
                        dtm.dbo.next[1] = self.config.enableDebugNdmreset and debug_regs.ndmreset
                        dtm.dbo.next[0] = True
                    elif dtm.adr == constants.DMI_ADDR_HARTINFO:
                        dtm.dbo.next[24:20] = self.config.num_dscratch
                        dtm.dbo.next[16:12] = self.config.numdata
                    elif dtm.adr == constants.DMI_ADDR_ABSTRACTAUTO:
                        dtm.dbo.next[16 + self.config.progbuf_size:16] = debug_regs.abstract_auto_progbuf
                        dtm.dbo.next[self.config.numdata:] = debug_regs.abstract_auto_data

                    # Program buffer and data window reads.
                    elif dtm.adr == constants.DMI_ADDR_PROGBUF0:
                        dtm.dbo.next = debug_regs.progbuf0
                        # autoexecprogbuf0: complete the register access and
                        # request the last abstract command again.
                        if debug_regs.abstract_auto_progbuf[0] and debug_regs.cmderr == constants.CMDERR_NONE:
                            if command_start_error != constants.CMDERR_NONE:
                                debug_regs.cmderr.next = command_start_error
                            else:
                                debug_regs.abstract_command_new.next = True
                    elif self.config.progbuf_size == 2 and dtm.adr == constants.DMI_ADDR_PROGBUF1:
                        dtm.dbo.next = debug_regs.progbuf1
                        # autoexecprogbuf1 mirrors progbuf0 handling for a
                        # two-entry program buffer.
                        if debug_regs.abstract_auto_progbuf[1] and debug_regs.cmderr == constants.CMDERR_NONE:
                            if command_start_error != constants.CMDERR_NONE:
                                debug_regs.cmderr.next = command_start_error
                            else:
                                debug_regs.abstract_command_new.next = True
                    elif is_data_reg:
                        data_index = dtm.adr - constants.DMI_ADDR_DATA0
                        dtm.dbo.next = debug_regs.data_regs[data_index]
                        # autoexecdataN returns the current dataN value for this
                        # DMI read and schedules the next abstract command. This
                        # is why repeated data0 reads can stream memory words.
                        if debug_regs.abstract_auto_data[data_index] and debug_regs.cmderr == constants.CMDERR_NONE:
                            if command_start_error != constants.CMDERR_NONE:
                                debug_regs.cmderr.next = command_start_error
                            else:
                                debug_regs.abstract_command_new.next = True

                    # Abstract command register block reads.
                    elif dtm.adr == constants.DMI_ADDR_ABSTRACTCS:
                        dtm.dbo.next[29:24] = self.config.progbuf_size
                        dtm.dbo.next[12] = debug_regs.abstract_command_state != t_abstract_command_state.none
                        dtm.dbo.next[11:8] = debug_regs.cmderr
                        dtm.dbo.next[4:] = self.config.numdata

                else:  # Write
                    # Control register writes.
                    if dtm.adr == constants.DMI_ADDR_DMCONTROL:
                        debug_regs.haltreq.next = debug_regs.hart_state == t_debug_hart_state.running and dtm.dbi[31]
                        if debug_regs.hart_state == t_debug_hart_state.halted and dtm.dbi[30]:
                            debug_regs.resumereq.next = True
                            debug_regs.resumeack.next = False

                        if self.config.enableDebugNdmreset:
                            debug_regs.ndmreset.next = dtm.dbi[1]

                    # Data and program buffer writes with optional autoexec.
                    elif is_data_reg:
                        data_index = dtm.adr - constants.DMI_ADDR_DATA0
                        debug_regs.data_regs[data_index].next = dtm.dbi
                        # Writes to dataN can also be autoexec triggers. The
                        # written value is visible to the command started here.
                        if debug_regs.abstract_auto_data[data_index] and debug_regs.cmderr == constants.CMDERR_NONE:
                            if command_start_error != constants.CMDERR_NONE:
                                debug_regs.cmderr.next = command_start_error
                            else:
                                debug_regs.abstract_command_new.next = True
                    elif dtm.adr == constants.DMI_ADDR_ABSTRACTCS:
                        debug_regs.cmderr.next = debug_regs.cmderr & ~dtm.dbi[11:8]
                    elif dtm.adr == constants.DMI_ADDR_ABSTRACTAUTO:
                        # abstractauto[15:0] selects dataN autoexec triggers.
                        # abstractauto[31:16] selects progbufN autoexec triggers.
                        debug_regs.abstract_auto_data.next = dtm.dbi[self.config.numdata:]
                        debug_regs.abstract_auto_progbuf.next = dtm.dbi[16 + self.config.progbuf_size:16]
                    elif dtm.adr == constants.DMI_ADDR_COMMAND:
                        if debug_regs.cmderr == constants.CMDERR_NONE:
                            if debug_regs.abstract_command_state != t_abstract_command_state.none:
                                debug_regs.cmderr.next = constants.CMDERR_BUSY
                            if debug_regs.hart_state == t_debug_hart_state.running:
                                debug_regs.cmderr.next = constants.CMDERR_HART_RUNNING
                            elif dtm.dbi[32:24] == 0:
                                debug_regs.command_type.next = t_abstract_command_type.access_reg
                                debug_regs.aarsize.next = dtm.dbi[23:20]
                                debug_regs.aarpostincrement.next = dtm.dbi[19]
                                debug_regs.postexec.next = dtm.dbi[18]
                                transfer = dtm.dbi[17]
                                debug_regs.transfer.next = transfer
                                debug_regs.write.next = dtm.dbi[16]
                                debug_regs.regno.next = dtm.dbi[5:0]

                                if dtm.dbi[23:20] == 2 and (
                                    dtm.dbi[16:5] == 0x80 or not transfer
                                ):
                                    debug_regs.abstract_command_new.next = True
                                else:
                                    debug_regs.cmderr.next = constants.CMDERR_NOT_SUPPORTED
                            else:
                                debug_regs.cmderr.next = constants.CMDERR_NOT_SUPPORTED
                    elif dtm.adr == constants.DMI_ADDR_PROGBUF0:
                        debug_regs.progbuf0.next = dtm.dbi
                        # Allow tools to update progbuf0 and immediately run the
                        # previously configured abstract command.
                        if debug_regs.abstract_auto_progbuf[0] and debug_regs.cmderr == constants.CMDERR_NONE:
                            if command_start_error != constants.CMDERR_NONE:
                                debug_regs.cmderr.next = command_start_error
                            else:
                                debug_regs.abstract_command_new.next = True
                    elif self.config.progbuf_size == 2 and dtm.adr == constants.DMI_ADDR_PROGBUF1:
                        debug_regs.progbuf1.next = dtm.dbi
                        # Same autoexec behavior for the optional second
                        # progbuf entry.
                        if debug_regs.abstract_auto_progbuf[1] and debug_regs.cmderr == constants.CMDERR_NONE:
                            if command_start_error != constants.CMDERR_NONE:
                                debug_regs.cmderr.next = command_start_error
                            else:
                                debug_regs.abstract_command_new.next = True

        return instances()
